language: java

# whitelist
branches:
  only:
    - prod
    - test
    - /^dev-.*$/ # any dev branch

script:
  - if [[ $TRAVIS_BRANCH =~ [/^dev-.*$/] ]];then
    BRANCH="DEV";
    else
    BRANCH=$TRAVIS_BRANCH;
    fi

script: mvn install -DskipTests=true

addons:
  artifacts:
    s3_region: "ap-southeast-2"
    paths:
      - $TRAVIS_BUILD_DIR/web/target/geonetwork.war
    target_paths: BRANCH

notifications:
  slack: geoscience-australia:gyVLDEprNplyAKYwDs7AFA0i
