language: java

script: mvn install -DskipTests=true
env:
  global:
  - ARTIFACTS_KEY = $DEV_AWS_ACCESS_KEY
  - ARTIFACTS_SECRET = $DEV_AWS_SECRET_KEY
  - ARTIFACTS_BUCKET = ecat-data

#deploy:
#  provider: s3
#  access_key_id: $DEV_AWS_ACCESS_KEY
#  secret_access_key: $DEV_AWS_SECRET_KEY
#  skip_cleanup: "true"
#  bucket: ecat-data
#  local_dir: "web/target/geonetwork.war"


addons:
  artifacts:
    # ...
    paths:
      - $HOME/web/target/geonetwork.war
