language: java

script: mvn install -DskipTests=true

env:
  - eval ARTIFACTS_BUCKET=\$${TRAVIS_BRANCH}_ARTIFACTS_BUCKET ARTIFACTS_KEY=\$${TRAVIS_BRANCH}_ARTIFACTS_KEY ARTIFACTS_SECRET=\$${TRAVIS_BRANCH}_ARTIFACTS_SECRET
  
addons:
  artifacts:
    s3_region: "ap-southeast-2"
    paths:
      - $TRAVIS_BUILD_DIR/web/target/geonetwork.war
    target_paths: war

after_script: 
- echo ARTIFACTS_KEY
- echo ARTIFACTS_SECRET
- echo ARTIFACTS_BUCKET
