language: java

script: mvn install -DskipTests=true

env:
  - ARTIFACTS_KEY="$%{$TRAVIS_BRANCH}_ARTIFACTS_KEY" ARTIFACTS_SECRET="$%{$TRAVIS_BRANCH}_ARTIFACTS_SECRET" ARTIFACTS_BUCKET="$%{$TRAVIS_BRANCH}_ARTIFACTS_BUCKET"

addons:
  artifacts:
    s3_region: "ap-southeast-2"
    paths:
      - $TRAVIS_BUILD_DIR/web/target/geonetwork.war
    target_paths: war

notifications:
  slack: geoscience-australia:gyVLDEprNplyAKYwDs7AFA0i
