language: java

script: mvn install -DskipTests=true

env:
  - if [ ${TRAVIS_BRANCH} == 'DEV' ]; then
      ARTIFACTS_BUCKET=$DEV_ARTIFACTS_BUCKET \
      ARTIFACTS_KEY=$DEV_ARTIFACTS_KEY \
      ARTIFACTS_SECRET=$DEV_ARTIFACTS_SECRET
    else
      ARTIFACTS_BUCKET=$TEST_ARTIFACTS_BUCKET ARTIFACTS_KEY=$TEST_ARTIFACTS_KEY ARTIFACTS_SECRET=$TEST_ARTIFACTS_SECRET
    fi
#  - eval ARTIFACTS_BUCKET=\$${TRAVIS_BRANCH}_ARTIFACTS_BUCKET ARTIFACTS_KEY=\$${TRAVIS_BRANCH}_ARTIFACTS_KEY ARTIFACTS_SECRET=\$${TRAVIS_BRANCH}_ARTIFACTS_SECRET
  
addons:
  artifacts:
    s3_region: "ap-southeast-2"
    paths:
      - $TRAVIS_BUILD_DIR/web/target/geonetwork.war
    target_paths: war

