language: java

script: mvn install -DskipTests=true

env:
  - ARTIFACTS_KEY="$$TRAVIS_BRANCH_ARTIFACTS_KEY" ARTIFACTS_SECRET="$$TRAVIS_BRANCH_ARTIFACTS_SECRET" ARTIFACTS_BUCKET="$$TRAVIS_BRANCH_ARTIFACTS_BUCKET"

addons:
  artifacts:
    s3_region: "ap-southeast-2"
    paths:
      - $TRAVIS_BUILD_DIR/web/target/geonetwork.war
    target_paths: war

